adam_epsilon: 1.0e-08
checkpoints_dir: null
checkpoints_dir_callback: /media/storage/checkpoints/korquad/2022-04-28/2022-04-28_13:55:48/epoch=05-val_loss=1.19.ckpt
data_dir: data/
data_file: data/KorQuAD_v1.0_dev.json
data_output_dir: .
do_lower_case: false
doc_stride: 128
eval_batch_size: 32
eval_splits: null
experiment_name: experiment
gradient_accumulation_steps: 3
gradient_cliping: 0.5
learning_rate: 5.0e-05
max_answer_length: 30
max_epochs: 10
max_query_length: 64
max_seq_length: 128
model_name_or_path: monologg/kobert
ngpu: 1
null_score_diff_threshold: 0.0
num_labels: null
output_dir: outputs/
prediction_file: outputs/predictions_.json
seed: 42
task_name: kobert
train_batch_size: 32
val_check_interval: 0.5
verbose_logging: false
version_2_with_negative: false
warmup_steps: 100
weight_decay: 0.04
